

SRC = src/scheduler.cpp \
      src/event.cpp \
      src/version.cpp \
      src/tagged-data.cpp \
      src/expect-buffer.cpp \
      src/delay-buffer.cpp \
      src/connector.cpp \

HDR = src/scheduler.h \
      src/simtime.h \
      src/event.h \
      src/property.h \
      src/version.h \
      src/tagged-data.h \
      src/expect-buffer.h \
      src/debug-log.h \
      src/delay-buffer.h \
      src/connector.h \

