

SRC = src/scheduler.cpp \
      src/event.cpp \
      src/version.cpp \
      src/tagged-data.cpp \
      src/expect-buffer.cpp \
      src/debug-log.cpp \
      src/delay-buffer.cpp \
      src/connector.cpp \
      src/tag-matcher.cpp \
      src/data-consumer.cpp\


HDR = src/scheduler.h \
      src/simtime.h \
      src/event.h \
      src/property.h \
      src/version.h \
      src/version-numbers.h \
      src/tagged-data.h \
      src/expect-buffer.h \
      src/debug-log.h \
      src/delay-buffer.h \
      src/connector.h \
      src/tag-matcher.h \
      src/data-destination.h \
      src/data-consumer.h \

